### ISSUE TITLE
Unable to use https/ssl

### ISSUE THREAD

**Issue by mbrookhuis** [uyuni-project/hub-xmlrpc-api#67]
When enabling ssl in the hub.conf and using https to connect there will be an error:
Traceback (most recent call last):
  File "hub_api_example_script.py", line 13, in <module>
    loginResponse = client.hub.loginWithAutoconnectMode(HUB_LOGIN, HUB_PASSWORD)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1303, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 607, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 836, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)

Using the following line:
HUB_URL = "https://hubmaster.mb.int:2830/hub/rpc/api"
HUB_LOGIN = "hubadmin"
HUB_PASSWORD = "suse1234"
client = xmlrpclib.Server(HUB_URL, verbose=0)
loginResponse = client.hub.loginWithAutoconnectMode(HUB_LOGIN, HUB_PASSWORD)

The certificate from the hub and all other SUSE Managers are in /etc/pki/trust/anchors and the update-ca-certificates script has run.

**Comment by moio** [comment]
I would suggest https should be provided by Apache/NGNIX or another web server, so I am closing the issue against this repo.
